

export enum userActionType {

    USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",

    USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",

    USER_LOGIN_FAIL = "USER_LOGIN_FAIL",

    USERS_LIST_REQUEST = "USERS_LIST_REQUEST",

    USERS_LIST_SUCCESS = "USERS_LIST_SUCCESS",

    USERS_LIST_FAIL = "USERS_LIST_FAIL"
}




export enum courseActionType {

    COURSE_ASSIGN_REQUEST = "COURSE_ASSIGN_REQUEST",

    COURSE_ASSIGN_SUCCESS = "COURSE_ASSIGN_SUCCESS",

    COURSE_ASSIGN_FAIL = "COURSE_ASSIGN_FAIL",

    COURSE_DELETE_FROM_USER_REQUEST = "COURSE_DELETE_FROM_USER_REQUEST",

    COURSE_DELETE_FROM_USER_SUCCESS = "COURSE_DELETE_FROM_USER_SUCCESS",

    COURSE_DELETE_FROM_USER_FAIL = "COURSE_DELETE_FROM_USER_FAIL",

    COURSE_DELETE_REQUEST = "COURSE_DELETE_REQUEST",

    COURSE_DELETE_SUCCESS = "COURSE_DELETE_SUCCESS",

    COURSE_DELETE_FAIL = "COURSE_DELETE_FAIL"
}


