

export enum userActionType {

    USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",

    USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",

    USER_LOGIN_FAIL = "USER_LOGIN_FAIL",

    USERS_LIST_REQUEST = "USERS_LIST_REQUEST",

    USERS_LIST_SUCCESS = "USERS_LIST_SUCCESS",

    USERS_LIST_FAIL = "USERS_LIST_FAIL",

    USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST",
    USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS",
    USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL",

    GET_PROJECTS_OF_USER_REQUEST = "GET_PROJECTS_OF_USER_REQUEST",

    GET_PROJECTS_OF_USER_SUCCESS = "GET_PROJECTS_OF_USER_SUCCESS",

    GET_PROJECTS_OF_USER_FAIL = "GET_PROJECTS_OF_USER_FAIL"
}






export enum courseActionType {

    COURSE_ASSIGN_REQUEST = "COURSE_ASSIGN_REQUEST",

    COURSE_ASSIGN_SUCCESS = "COURSE_ASSIGN_SUCCESS",

    COURSE_ASSIGN_FAIL = "COURSE_ASSIGN_FAIL",

    COURSE_DELETE_FROM_USER_REQUEST = "COURSE_DELETE_FROM_USER_REQUEST",

    COURSE_DELETE_FROM_USER_SUCCESS = "COURSE_DELETE_FROM_USER_SUCCESS",

    COURSE_DELETE_FROM_USER_FAIL = "COURSE_DELETE_FROM_USER_FAIL",

    COURSE_DELETE_REQUEST = "COURSE_DELETE_REQUEST",

    COURSE_DELETE_SUCCESS = "COURSE_DELETE_SUCCESS",

    COURSE_DELETE_FAIL = "COURSE_DELETE_FAIL",

    COURSE_NOT_ASSIGN_REQUEST = "COURSE_NOT_ASSIGN_REQUEST",

    COURSE_NOT_ASSIGN_SUCCESS = "COURSE_NOT_ASSIGN_SUCCESS",

    COURSE_NOT_ASSIGN_FAIL = "COURSE_NOT_ASSIGN_FAIL"
}


